Fix exception thrown for domain-less URLs
`urlObj.hostname` can be `null` when called with URLs like "/foo".

This will cause the following exception to be thrown from punycode:
```
TypeError: Cannot read property 'split' of null
  at mapDomain (punycode.js:98:21)
  at Object.toUnicode (punycode.js:454:10)
```

This diff fixes that by checking that the hostname exists.